baseURL: 'https://wojtazk.github.io'
theme: 'terminalcv'
title: 'wojtazk'

params:
  version: '1.0.0'
  description: 'My online resume'
  blog: false
  prompt:
    core:
      text: 'root@wojtazk-github-io'
      color: '#8AE234'
      before: '['
      beforeColor: '#cc0000'
      # after: '\]'
      afterColor: '#cc0000'
      separator: '-'
    # separator:
    #   text: ' in'
    #   color: 'grey'
    path:
      # before: '['
      before: ' '
      beforeColor: '#cc0000'
      text: '~/resume_exe'
      color: '#729FCF'
      after: '\]'
      afterColor: '#cc0000'
    extra:
      text: '# '
      color: 'grey'

  # promptColor: grey
  # promptSimbols: ':~$'
  # promptSimbolsColor: grey
  startxLocation: ./gui
  # useLess: true
  listLS: true
  # exitLocation: 'about:blank'
  exitMessage: '[Session completed, the browser window can be safely closed]'
  source: false
  #use a ‎ (blank character) if your first character of the ascii art is a whitespace
  greeting: |
    ‎                   __  __                  __    
    .--.--.--..-----. |__||  |_ .---.-..-----.|  |--.
    |  |  |  ||  _  | |  ||   _||  _  ||-- __||    < 
    |________||_____| |  ||____||___._||_____||__|__|
                     |___|                               
                                                                
    Welcome to my online resume

    Type 'help' for a list of available commands

  bootsequence: |
    [0.000000] User request detected
    [0.001234] Reserving Holy Cloud Resources
    [0.002345] Networking Sacristy Initializing... [ OK ]
    [0.003456] Cloud Instance spin-up requested... [ AMEN ]

    [0.009012] :: Initializing Vatican Linux components
    [0.011234] Vaticanux 6.6.6-arch1-1-ECCLESIA (pontifex@sanctum) (gcc (GCC) 12.1.0)
    [0.012345] Command line: BOOT_IMAGE=/boot/vmlinuz-holy root=/dev/cloud/disk rw quiet godlevel=3

    [0.020123] [  OK  ] Started VaticanOS_Boot1 (Incantation) Service.
    [0.021234] [  OK  ] Started VaticanOS_Boot2 (Benediction) Service.
    [0.022345] [  OK  ] Started Holy Webserver Service (Basilica-NGINX).
    [0.026789] [  OK  ] Started The 'Hire Me' Daemon (Blessed).

    [0.027890] Welcome to TerminalCV.
    [0.028901] Boot Complete. May your journey be blessed.

  whois:
    # settings:
    #   useLess: true
    details:
      name: 'Wojciech Kowal'
      profession: 'Cybersec Student'
      location: 'Wrocław, Poland'
      email: 'wojtazk@duck.com'
      homelink: 'https://wojtazk.github.io'
      description: |
        My code never has bugs, just undocumented features.

  social:
    # settings:
    #   useLess: true
    #   hideName: true
    details:
      - name: 'GitHub'
        url: 'https://github.com/wojtazk'
      - name: 'LinkedIn'
        url: 'https://www.linkedin.com/in/kowal-wojciech/'
      - name: 'TryHackMe'
        url: 'https://tryhackme.com/p/wojtazk'
      - name: 'Codecademy'
        url: 'https://www.codecademy.com/profiles/wojtazk'

  work:
    # settings:
    #   useLess: true
    details:
      - jobTitle: Intern in Network Maintenance Department
        color: red
        company: Wrocław Centre for Networking and Supercomputing
        location: Wrocław, Poland
        date: May 2025 - June 2025 (2 months)
        description: Internship (part of first-level studies)

      - jobTitle: Intern at Computer Repair Shop
        color: green
        company: WMPnet
        location: Toruń, Poland
        date: July 2021 - July 2021 (1 month)
        description: Internship (part of Toruń + EU project "Dobry zawód - dobry staż")

      - jobTitle: Intern in IT Department
        color: lightblue
        company: Neuca S.A.
        location: Toruń, Poland
        date: May 2021 - May 2021 (1 month)
        description: Internship (part of secondary school)

  education:
    details:
      - courseName: Wrocław University of Science and Technology
        color: red
        date: Oct 2022 - Present (Expected in Feb 2026)
        description: first-level studies, full-time studies | Cybersecurity

      - courseName: Zespół Szkół Mechanicznych Elektrycznych i Elektronicznych im. prof. Sylwestra Kaliskiego w Toruniu
        color: green
        date: Sept 2018 - Apr 2022
        description: secondary school | Technik Informatyk (IT Technician)

  skills:
    # settings:
    #   useLess: true
    details:
      - name: Linux
        percentage: 70
        description: I use Arch btw

      - name: Windows
        percentage: 50
        description: Yeah, Linux is better :)

      - name: Networking
        percentage: 65
        description: Surrounded by Cisco staff, I personally rely on a MikroTik Router.

      - name: Git
        percentage: 65

      - name: GitHub
        percentage: 65

      - name: Docker
        percentage: 65

      - name: AWS
        percentage: 20

      - name: Python
        percentage: 70

      - name: Bash
        percentage: 60

      - name: C++
        percentage: 50

      - name: SQL
        percentage: 60

      - name: HTML, CSS, JavaScript
        percentage: 75

      - name: React.js
        percentage: 65

  softskills:
    # settings:
    #   useLess: true
    details:
      - name: Problem-Solving
        # color: red
        percentage: 75
        #description:

      - name: Communication
        # color: green
        percentage: 70
        # description: Description

      - name: Teamwork
        # color: lightblue
        percentage: 70
        # description: Description

  languages:
    # settings:
    #   useLess: true
    details:
      - name: Polish
        color: Red
        percentage: 100
        description: Cześć!

      - name: English
        color: Green
        percentage: 85
        description: Hello there!

      - name: Klingon
        color: lightblue
        percentage: 0
        description: nuqneH?

  projects:
    # settings:
    #   useLess: true
    details:
      - title: test-cross-platform
        color: red
        date: 2025
        link: https://github.com/wojtazk/testo-cross-platform
        description: 'Cross-platform implementation of popular quiz app at PWR, technologies used: Tauri + Vite + Ionic + React'

      - title: dazy-banych
        color: green
        date: 2024
        link: https://github.com/wojtazk/dazy-banych
        description: 'Database course project, technologies used: PostgreSQL, Python + Flask, Next.js + HeroUI'

      - title: Phishing Awareness Simulation Tool
        color: lightblue
        date: 2025
        link: https://github.com/OsinsqLew/Phishing-Awareness-Simulation-Tool-
        description: 'Team Project for University: I was responsible for phishing email generation, containerizing the application, and deploying it on AWS.'

      - title: And many more :)
        # color: lightblue
        date: all the time
        link: https://github.com/wojtazk
        description: Check them out!

  certifications:
    # settings:
    #   useLess: true
    details:
      - certName: SOC Level 1 Certificate
        company: TryHackMe
        date: Jan 2026
        badge: https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-2PVXDJ1SGF.pdf
        #description: Lorem Ipsum

      - certName: Advent of Cyber 2025 Certificate
        company: TryHackMe
        date: Dec 2025
        badge: https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-KDVTLIAHSG.pdf
        #description: Lorem Ipsum
    
      - certName: Web Application Pentesting Certificate
        company: TryHackMe
        date: Sep 2025
        badge: https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-LS3LJ6CUUV.pdf
        #description: Lorem Ipsum
        
      - certName: Web Fundamentals Certificate
        company: TryHackMe
        date: Aug 2025
        badge: https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-9HA9JWLMRW.pdf
        #description: Lorem Ipsum
        
      - certName: Jr Penetration Tester Certificate
        company: TryHackMe
        date: Aug 2025
        badge: https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-NQTA8WIJBW.pdf
        #description: Lorem Ipsum

      - certName: Cyber Security 101 Certificate
        company: TryHackMe
        date: Jul 2025
        badge: https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-31SPZFNLDG.pdf
        #description: Lorem Ipsum
    
      - certName: Network Security (Course Completion)
        company: Wrocław University of Science and Technology
        date: Jun 2025
        badge: https://www.credly.com/badges/6a60c7cf-dffe-42c9-82c7-ca5cf99c1ac3/public_url
        #description: Lorem Ipsum

      - certName: Pre Security Certificate
        company: TryHackMe
        date: Jun 2025
        badge: https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-AXIQVSVAKR.pdf
        #description: Lorem Ipsum

      - certName: 'CCNA: Enterprise Networking, Security, and Automation (Course Completion)'
        company: Wrocław University of Science and Technology
        date: Feb 2025
        badge: https://www.credly.com/badges/146434a6-441d-4ea6-be5b-14a469ba633c/public_url
        #description: Lorem Ipsum

      - certName: 'CCNA: Switching, Routing, and Wireless Essentials (Course Completion)'
        company: Wrocław University of Science and Technology
        date: Jul 2024
        badge: https://www.credly.com/badges/f02a86ed-51ac-423d-acff-d17743b6bfea/public_url
        #description: Lorem Ipsum

      - certName: 'CCNA: Introduction to Networks (Course Completion)'
        company: Wrocław University of Science and Technology
        date: Jul 2024
        badge: https://www.credly.com/badges/3171c619-ec2b-4716-a69b-7edb5e43c30d/public_url
        #description: Lorem Ipsum

      - certName: 'Derive Insights from BigQuery Data Skill Badge'
        company: Google Cloud
        date: Sep 2024
        badge: https://www.credly.com/badges/bc53c6f8-35fc-499c-8a45-315584ad0779/public_url
        #description: Lorem Ipsum

      - certName: 'Learn Python 3 Course (Course Completion)'
        company: Codecademy
        date: Oct 2023
        badge: https://www.codecademy.com/profiles/wojtazk/certificates/6c152bd262967f8c941c9707ed636bda
        #description: Lorem Ipsum

      - certName: 'Learn Git & GitHub Course (Course Completion)'
        company: Codecademy
        date: Sep 2023
        badge: https://www.codecademy.com/profiles/wojtazk/certificates/a8ab218d5950c29861635cc0bf12fd13
        #description: Lorem Ipsum

      - certName: 'Learn the Command Line Course (Course Completion)'
        company: Codecademy
        date: Aug 2023
        badge: https://www.codecademy.com/profiles/wojtazk/certificates/c87ba0541f8be78bc2f4ba1128233f6f
        #description: Lorem Ipsum

      - certName: 'Learn JavaScript Unit Testing Course (Course Completion)'
        company: Codecademy
        date: Jan 2023
        badge: https://www.codecademy.com/profiles/wojtazk/certificates/f4276e8c08a3ba174ef0147deb0c3013
        #description: Lorem Ipsum

      - certName: 'Learn JavaScript Course (Course Completion)'
        company: Codecademy
        date: Jan 2023
        badge: https://www.codecademy.com/profiles/wojtazk/certificates/705dcb15de0da4dd9d9fc4f3274b430e
        #description: Lorem Ipsum

      - certName: 'Learn C++ Course (Course Completion)'
        company: Codecademy
        date: Oct 2022
        badge: https://www.codecademy.com/profiles/wojtazk/certificates/b74a2390dfc4127fa5d43fe147425ad0
        #description: Lorem Ipsum

      - certName: 'React - The Complete Guide (incl Hooks, React Router, Redux) (Course Completion)'
        company: Udemy
        date: Aug 2022
        badge: https://www.udemy.com/certificate/UC-a6980186-e536-443c-b898-6842cae07960/
        #description: Lorem Ipsum

      - certName: 'The Complete JavaScript Course 2022: From Zero to Expert! (Course Completion)'
        company: Udemy
        date: Jul 2022
        badge: https://www.udemy.com/certificate/UC-797288db-757f-468d-bf5d-fa37bbd49b42/
        #description: Lorem Ipsum

      - certName: 'The Complete Ethical Hacking Course: Beginner to Advanced! (Course Completion)'
        company: Udemy
        date: Nov 2021
        badge: https://www.udemy.com/certificate/UC-3f8f185a-4d45-43f8-8f33-6221ec2724db/
        #description: Lorem Ipsum

      - certName: 'C++ od Podstaw do Eksperta (Course Completion)'
        company: Udemy
        date: Aug 2021
        badge: https://www.udemy.com/certificate/UC-a8e59611-f902-4767-a217-03d2b6a55618/
        #description: Lorem Ipsum

      - certName: 'Introduction to Cybersecurity (Course Completion)'
        company: Zespół Szkół Mechanicznych Elektrycznych i Elektronicznych im. prof. Sylwestra Kaliskiego w Toruniu
        date: Jun 2020
        badge: https://www.credly.com/badges/f185a7ec-ed1a-4805-99da-af1384f8a36d/public_url
        #description: Lorem Ipsum

      - certName: 'Learn Linux in 5 Days and Level Up Your Career (Course Completion)'
        company: Udemy
        date: Jan 2020
        badge: https://www.udemy.com/certificate/UC-R1VLNRLM/
        #description: Lorem Ipsum

  misc:
    # settings:
    #   useLess: true
    commandName: invasion
    title: 'alien invasion'
    titleColor: '#F83B3A'
    content: |
      ‎
            ##      ##        ) )
          ##############
        ####  ######  ####
      ######################
      ##  ##############  ##    )  )
      ##  ##          ##  ##
            ####  ####

    contentColor: '#42E9F4'
